this_file <- tryCatch(normalizePath(sys.frame(1)$ofile, winslash = "/", mustWork = TRUE), error = function(e) NA_character_)
if (is.na(this_file)) this_file <- file.path(getwd(), "local-r", "run.R")
repo <- normalizePath(file.path(dirname(this_file), ".."), winslash = "/", mustWork = TRUE)
if (!requireNamespace("plumber", quietly = TRUE)) install.packages("plumber")
if (!requireNamespace("jsonlite", quietly = TRUE)) install.packages("jsonlite")
Sys.setenv(CHARTFORGE_APP_DIR = file.path(repo, "inst", "app"))
options(chartforge.data_env = .GlobalEnv)
pr <- plumber::plumb(file.path(repo, "inst", "plumber", "plumber.R"))
if (is.function(pr$setDocs)) pr$setDocs(FALSE)
if (is.function(pr$setDocsCallback)) pr$setDocsCallback(NULL)
url <- "http://127.0.0.1:8788"
message("ChartForge listening at ", url)
utils::browseURL(url)
pr$run(host = "127.0.0.1", port = 8788, docs = FALSE, swaggerCallback = function(url) invisible(NULL))
